#define MY_FONT_PATH  "arial.ttf"
#define GAMEFIELD_PATH "gamefield.jpg"
#define APP_TITLE "Polipoly"
#define FIELDINFO_TEX_PATH "field.jpg"
#define FIELDDATA_PATH "fielddata.txt"
#define FIELDINFO_X 768
#define FIELDINFO_Y 3
#define FIELDCOLOR_SIZEX 247
#define FIELDCOLOR_SIZEY 50
#define FIELDCOLOR_X 771
#define FIELDCOLOR_Y 6
#define SCREEN_X 1024
#define SCREEN_Y 768
#define TEAMNAME_X 774
#define TEAMNAME_Y 9
#define FIELDNAME_X 774
#define FIELDNAME_Y 30
