#pragma once
#define MY_FONT_PATH  "arial.ttf"
#define GAMEFIELD_PATH "Interface.bmp"
#define APP_TITLE "Polipoly"
#define FIELDINFO_TEX_PATH "field.jpg"
#define FIELDDATA_PATH "fielddata.txt"
#define DICE_PIC_ONE "Dice_1.png"
#define DICE_PIC_TWO "Dice_2.png"
#define DICE_PIC_THREE "Dice_3.png"
#define DICE_PIC_FOUR "Dice_4.png"
#define DICE_PIC_FIVE "Dice_5.png"
#define DICE_PIC_SIX "Dice_6.png"
#define DICE_PIC_IDLE "Dice_0.png"
#define PLAYER_1_PATH "Pionek1.png"
#define PLAYER_2_PATH "Pionek2.png"
#define PLAYER_3_PATH "Pionek3.png"
#define PLAYER_4_PATH "Pionek4.png"
#define FIELDINFO_X 768
#define FIELDINFO_Y 3
#define FIELDCOLOR_SIZEX 247
#define FIELDCOLOR_SIZEY 50
#define FIELDCOLOR_X 771
#define FIELDCOLOR_Y 6
#define CONTENT_X 780
#define CONTENT_Y 60
#define SCREEN_X 1024
#define SCREEN_Y 768
#define TEAMNAME_X 774
#define TEAMNAME_Y 9
#define FIELDNAME_X 774
#define FIELDNAME_Y 30
#define GAMEFIELD_SIZE 40
#define DICE1_X 900
#define DICE1_Y 600
#define DICE2_X 960 
#define DICE2_Y 600
#define FIELDNAME_TEXT_SIZE 13
#define TEAMNAME_TEXT_SIZE 12
#define CONTENT_TEXT_SIZE 10
#define PIN_WIDTH 26
#define PIN_HEIGHT 26
#define DICE_SIZE 60
#define PLAYERS 4
#define INITIAL_CASH 1500
#define MOVE_INTERVAL 500
